// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_ldm
void rcpp_ldm(Rcpp::DataFrame xyz_in, float hs, float ht, int res_sp, int res_t);
RcppExport SEXP _stkde_rcpp_ldm(SEXP xyz_inSEXP, SEXP hsSEXP, SEXP htSEXP, SEXP res_spSEXP, SEXP res_tSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type xyz_in(xyz_inSEXP);
    Rcpp::traits::input_parameter< float >::type hs(hsSEXP);
    Rcpp::traits::input_parameter< float >::type ht(htSEXP);
    Rcpp::traits::input_parameter< int >::type res_sp(res_spSEXP);
    Rcpp::traits::input_parameter< int >::type res_t(res_tSEXP);
    rcpp_ldm(xyz_in, hs, ht, res_sp, res_t);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stkde_rcpp_ldm", (DL_FUNC) &_stkde_rcpp_ldm, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_stkde(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
