// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_stkde
arma::cube rcpp_stkde(Rcpp::DataFrame xyt_in, float hs, float ht, int x_size, int y_size, int t_size);
RcppExport SEXP _stkde_rcpp_stkde(SEXP xyt_inSEXP, SEXP hsSEXP, SEXP htSEXP, SEXP x_sizeSEXP, SEXP y_sizeSEXP, SEXP t_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type xyt_in(xyt_inSEXP);
    Rcpp::traits::input_parameter< float >::type hs(hsSEXP);
    Rcpp::traits::input_parameter< float >::type ht(htSEXP);
    Rcpp::traits::input_parameter< int >::type x_size(x_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type y_size(y_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type t_size(t_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_stkde(xyt_in, hs, ht, x_size, y_size, t_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stkde_rcpp_stkde", (DL_FUNC) &_stkde_rcpp_stkde, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_stkde(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
