# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' stkde
#'
#' Calculates a spatiotemporal kernel density estimation (STKDE) for a given
#' point.
#'
#' @param x X coordinate of event.
#' @param y y coordinate of event.
#' @param t T coordinate of event.
#' @param xi X coordinate of grid point.
#' @param yi Y coordinate of grid point.
#' @param ti T coordinate of grid point.
#' @param hs Spatial bandwidth.
#' @param ht Temporal bandwidth.
#'
#' @return stkde value
#'
#' @noRd
NULL

#' rcpp_stkde
#'
#' Calculates a spatiotemporal kernel density estimation (STKDE) and returns it
#' as a 3D-array
#'
#' @param xyt_in \code{data.frame} containing the x, y and t coordinates of the
#' input data (projected coordinates).
#' @param hs Spatial bandwidth in m.
#' @param ht Temporal bandwidth.
#' @param x_size Spatial x dimension of output array.
#' @param y_size Spatial y dimension of output array.
#' @param t_size Temporal t dimension of output array.
#'
#' @return \code{arma::cube} object containing all STKDE values.
#'
#' @noRd
rcpp_stkde <- function(xyt_in, hs, ht, x_size, y_size, t_size) {
    .Call(`_stkde_rcpp_stkde`, xyt_in, hs, ht, x_size, y_size, t_size)
}

