# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' stkde
#'
#' Calculates the spatiotemporal 
#'
#' @param coords \code{arma::mat} object with x and y coordinates in the
#' columns.
#'
#' @return the linear directional mean.
#'
#' @noRd
NULL

#' rcpp_stkde
#'
#' Calculates a spatiotemporal kernel density estimation (STKDE).
#'
#' @param pts_x X coordinates of input data.
#' @param pts_y Y coordinates of input data.
#' @param pts_z Z coordinates of input data.
#' @param hs Spatial bandwidth.
#' @param ht Temporal bandwidth.
#'
#' @noRd
rcpp_ldm <- function(xyz_in, hs, ht, res_sp, res_t) {
    invisible(.Call(`_stkde_rcpp_ldm`, xyz_in, hs, ht, res_sp, res_t))
}

